site_name: Liveness
site_description: Liveness(Face anti spoofing)
site_author: Nivratti Boyane

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: amber
  highlightjs: true

nav:
- index.md
- Installation:
  - centos:
    - installation/centos/opencv.md
    - installation/centos/phpcpp.md
  - ubuntu:
    - installation/ubuntu/opencv.md
    - installation/ubuntu/phpcpp.md
- download-models.md
- build_liveness.md
- serve_liveness.md
- generating-shared-library.md
- using-shared-library.md
- test-liveness.md
- how-to-update.md

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed

extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js